<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  // wrapped into
  // 网络请求: aaa
  // 处理: aaa111
  // 处理: aaa111222

  // new Promise((resolve,reject) => {
  //   setTimeout(() =>{
  //     resolve('aaa')
  //   },1000)
  // }).then(res => {
  //   // 1
  //   console.log(res,'第一次处理')
  //   // 2
  //   return new Promise((resolve) => {
  //     resolve(res + '111')
  //   })
  // }).then(res => {
  //   console.log(res,'第二次处理')
  //   return new Promise(resolve => {
  //     resolve(res + '222')
  //   })
  // }).then(res => {
  //   console.log(res, '第三次处理')
  // })

  // new Promise(resolve => resolve(结果))简写
  // new Promise((resolve,reject) => {
  //   setTimeout(() =>{
  //     resolve('aaa')
  //   },1000)
  // }).then(res => {
  //   // 1
  //   console.log(res,'第一次处理')
  //   // 2
  //   return Promise.resolve(res + '111')
  // }).then(res => {
  //   console.log(res,'第二次处理')
  //   return Promise.resolve(res + '222')
  // }).then(res => {
  //   console.log(res, '第三次处理')
  // })

  // 省略Promise.resolve
  new Promise((resolve,reject) => {
    setTimeout(() =>{
      resolve('aaa')
    },1000)
  }).then(res => {
    // 1
    console.log(res,'第一次处理')
    // 2
    return res + '111'
  }).then(res => {
    console.log(res,'第二次处理')
    return res + '222'
  }).then(res => {
    console.log(res, '第三次处理')
  })

  new Promise((resolve,reject) => {
    setTimeout(() =>{
      resolve('aaa')
    },1000)
  }).then(res => {
    // 1
    console.log(res,'第一次处理')
    // 2
    // return Promise.reject('error message')
    throw 'error message'
  }).then(res => {
    console.log(res,'第二次处理')
    return res + '222'
  }).then(res => {
    console.log(res, '第三次处理')
  }).catch(err => {
    console.log(err);
  })
</script>
</body>
</html>